
# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: xskokernel/kernel_build_action@main
        with:
          kernel-url: https://github.com/xskokernel/K34pure.git
          kernel-dir: msm-4.14
          kernel-branch: 15-pure
          config: phoenix_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
